.\" ========================================================================
.\"
.IX Title "EMPTYVSS.1 1"
.TH EMPTYVSS.1 1 "2018-11-05" 
.SH "NAME"
emptyvss \- Checking for Missing Verses
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBemptyvss\fR module
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
A command line utility which find verses in a module that contain no text,
since this may indicate errors in the module.
Just run \*(L"emptyvss <module name>\*(R" to generate a list.
.SH "Authors"
.IX Header "Authors"
This manual page was written by the Debian Crosswire Packaging Team
<pkg\-crosswire\-devel@lists.alioth.debian.org> for Debian project but
may be used by others.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
