.\" ========================================================================
.\"
.IX Title "IMP2VS.1 1"
.TH IMP2VS.1 1 "2018-11-05"
.SH "NAME"
imp2vs \- Bible/Commentary module creation tool
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBimp2vs\fR <\s-1FILE\s0> [\s-1PATH\s0]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
A command line utility to convert imp formatted file Bible/Commentary \s-1SWORD\s0
module.
.SH "OPTIONS"
.IX Header "OPTIONS"
.IP "\fB[\s-1PATH\s0]\fR" 4
.IX Item "[PATH]"
Specify path for the output module if different from the input file.
.SH "Authors"
.IX Header "Authors"
This manual page was written by Dmitrijs Ledkovs <dmitrij.ledkov@gmail.com> for
Debian project but may be used by others.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
