.\" ========================================================================
.\"
.IX Title "IMP2LD.1 1"
.TH IMP2LD.1 1 "2018-11-05"
.SH "NAME"
imp2ld \- Lexicon, Dictionary, Daily Devotional and Glossary module creation tool
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBimp2ld\fR <\s-1FILE\s0> [modulename] [4 | 2 | z]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
A command line utility to convert imp formatted file into lexicon, dictionary,
daily devotional or glossary \s-1SWORD\s0 module.
.SH "OPTIONS"
.IX Header "OPTIONS"
.IP "\fB[modulename]\fR" 4
.IX Item "[modulename]"
Specify the output modulename.
.IP "\fB[4 | 2 | z\fR" 4
.IX Item "[4 | 2 | z"
Specify output module driver. Default is 4.
.SH "Authors"
.IX Header "Authors"
This manual page was written by Dmitrijs Ledkovs <dmitrij.ledkov@gmail.com> for
Debian project but may be used by others.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
