.\" ========================================================================
.\"
.IX Title "MKFASTMOD.1 1"
.TH MKFASTMOD.1 1 "2018-11-05"
.SH "NAME"
mkfastmod \- creates a search index for a module
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
\&\fBmkfastmod\fR module
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
A command line utility which creates a search index for a module.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
