.\" ========================================================================
.\"
.IX Title "VS2OSISREF.1 1"
.TH VS2OSISREF.1 1 "2018-11-05"
.SH "NAME"
vs2osisref \- a tool to convert verse references from English to OSIS
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
vs2osisref \s-1VERSEREF\s0 [verse_context]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
Returns the osisRef of a given (text form) verse reference.
.SH "Authors"
.IX Header "Authors"
This manual page was written by Dmitrijs Ledkovs <dmitrij.ledkov@gmail.com> for
Debian project but may be used by others.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
