.\" ========================================================================
.\"
.IX Title "VS2OSISREFTXT.1 1"
.TH VS2OSISREFTXT.1 1 "2018-11-05"
.SH "NAME"
vs2osisreftxt \- a tool that probably does something with OSIS refs
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
vs2osisreftxt \s-1STRING\s0 [local_name] [test\-in\-set\-verse]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
Apart from synopsis, little is know what this does. Probably something
to do with parsing verses or verse references to/from string to/from
\&\s-1OSIS\s0 in a given locale or something along the lines. Email me if you
can give better description of what this util does.
.SH "Authors"
.IX Header "Authors"
This manual page was written by Dmitrijs Ledkovs <dmitrij.ledkov@gmail.com> for
Debian project but may be used by others.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
vs2osisref
