perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_aa.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ach.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_af.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ar.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_as.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_az.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_be.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_bfo.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_bg.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_bn.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_bo.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_bs.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_cs.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_csb.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_cy.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_da.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_de.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_dv.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_el.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_es.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_et.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fa.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ff.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fi.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fil.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fj.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fo.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_fy.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ga.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_gl.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_gu.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ha.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_hi.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_hr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_hu.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_hy.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_in.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_is.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_it.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_iw.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ja.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ka.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_kk.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_km.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ko.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ku.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ky.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_lg.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ln.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_lt.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_luy.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_lv.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mai.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mg.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mi.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mk.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ml.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mn.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ms.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_mt.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ne.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_nl.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_no.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_nr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_nso.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_or.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_pa.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_pl.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_pt.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ro.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ru.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ry.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_si.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sk.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sl.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_son.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sq.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ss.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_st.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sv.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_sw.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ta.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_te.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_th.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_tl.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_tn.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_tr.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ts.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_tt.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ug.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_uk.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ur.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_uz.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_ve.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_vi.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_vls.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_zh.properties
perl moveKeys.pl OldHtmlBundle.properties HtmlBundle_zh_TW.properties
