cd /c/temp/sitemaps

curl http://localhost:8080/step-web/SITEMAP_BIBLE_A.xml > A.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_B.xml > B.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_C.xml > C.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_D.xml > D.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_E.xml > E.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_F.xml > F.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_G.xml > G.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_H.xml > H.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_I.xml > I.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_J.xml > J.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_K.xml > K.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_L.xml > L.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_M.xml > M.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_N.xml > N.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_O.xml > O.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_P.xml > P.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_Q.xml > Q.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_R.xml > R.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_S.xml > S.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_T.xml > T.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_U.xml > U.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_V.xml > V.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_W.xml > W.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_X.xml > X.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_Y.xml > Y.out
curl http://localhost:8080/step-web/SITEMAP_BIBLE_Z.xml > Z.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_A.xml > cA.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_B.xml > cB.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_C.xml > cC.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_D.xml > cD.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_E.xml > cE.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_F.xml > cF.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_G.xml > cG.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_H.xml > cH.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_I.xml > cI.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_J.xml > cJ.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_K.xml > cK.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_L.xml > cL.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_M.xml > cM.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_N.xml > cN.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_O.xml > cO.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_P.xml > cP.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_Q.xml > cQ.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_R.xml > cR.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_S.xml > cS.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_T.xml > cT.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_U.xml > cU.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_V.xml > cV.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_W.xml > cW.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_X.xml > cX.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_Y.xml > cY.out
curl http://localhost:8080/step-web/SITEMAP_COMMENTARY_Z.xml > cZ.out

for file in `ls *.out` ; do echo $file ;  awk '/<url>/{x++}END{print x}' RS="localhost" $file ; done
